title: Notes about Networking
logo: /assets/img/logo.png
description: learning Networking
show_downloads: false
google_analytics:
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
