title: Networking
description: "Learning Networking"
author:
  name: "Codetime"
  # email: "to be updated"
  # url: ""

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
#plugins:
#  - jekyll-seo-tag
#  - jekyll-paginate
# - jekyll-sitemap

# Custom variables
owner : "Codetime"
year : "2024"

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
