title: Networking
description: "Learning Networking"
show_downloads: false
author:
  name: "Codetime"
  # email: "to be updated"
  # url: ""

# Custom variables
owner : "Codetime"
year : "2024"

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

github:
  zip_url: http://example.com/download.zip
  another_url: another value
