title: Networking
description: "Learning Networking"
show_downloads: true
author:
  name: "Codetime"
  # email: "to be updated"
  # url: ""

# Custom variables
owner : "Codetime"
year : "2024"

theme: jekyll-theme-hacker
plugins:
- jekyll-remote-theme

github:
  zip_url: http://example.com/download.zip
 # another_url: http://example.com/
 # url: http://example.com/
